local LeftRightHotkey = require("spoons/LeftRightHotkey")
require("spoons/Reload")
require("spoons/Rcmd")
require("spoons/Jk")
-- require("spoons/DisableKeys")
-- require("spoons/Remap")
-- require("spoons/Spaces")
-- require("spoons/ControlEscape")

LeftRightHotkey:start()
