-- https://github.com/nvim-treesitter/nvim-treesitter
return {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
        -- config = function(_, opts)
        opts.auto_install = true
        opts.ensure_installed = {
            "awk",
            "bash",
            "bibtex",
            "c",
            "clojure",
            "cmake",
            "commonlisp",
            "cpp",
            "css",
            "dart",
            "diff",
            "dockerfile",
            "erlang",
            "fish",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "go",
            "gomod",
            "graphql",
            "hcl",
            "html",
            "http",
            "java",
            "javascript",
            "jq",
            "jsdoc",
            "json",
            "jsonc",
            "jsonnet",
            "kotlin",
            "latex",
            "lua",
            "make",
            "markdown",
            "markdown_inline",
            "perl",
            "php",
            "python",
            "r",
            "regex",
            "rst",
            "ruby",
            "rust",
            "scala",
            "scss",
            "solidity",
            "sql",
            "swift",
            "terraform",
            "todotxt",
            "toml",
            "tsx",
            "typescript",
            "vim",
            "vue",
            "yaml",
        }
        return opts
    end
}
