#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (tmux list-windows -F "#W") | fzf --prompt='  Tmux window  ' --border=none --exit-0 )
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux switch-client -t ":$selected"
