#!/usr/bin/env bash

# Reference:
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (zoxide query --list | grep "$HOME"; find ~/git ~/work ~/projects ~/temp ~/.config ~/.local ~ -mindepth 1 -maxdepth 1 -type d) | sed "s|$HOME|~|g" | awk '!x[$0]++' | fzf --prompt='  Tmux window  ' --border=none --exit-0 | sed "s|~|$HOME|g")
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)


if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    exit 0
fi

tmux new-window -c "$selected"
