#!/usr/bin/env bash

# Reference:
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (zoxide query --list --score | grep "$HOME";) | sed "s|$HOME|~|g" | awk '!x[$0]++' | fzf --scheme history --prompt='  Tmux window  ' --border=none --exit-0 | sed "s|~|$HOME|g" | awk '{ print $2 }')
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
