#!/usr/bin/env bash

# Reference:
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (zoxide query --list --score | grep "$HOME";) | sed "s|$HOME|~|g" | awk '!x[$0]++' | fzf --scheme history --prompt='  Tmux window  ' --border=none --exit-0 | sed "s|~|$HOME|g" | awk '{ print $2 }')

fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)


if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    exit 0
fi

tmux new-window -c "$selected"
