#!/usr/bin/env bash

# Reference:
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$( (
		zoxide query --list
		find ~/git ~/work ~/projects ~/temp ~/.config ~/.local ~ -mindepth 1 -maxdepth 1 -type d
	) | awk '!x[$0]++' | fzf --prompt='  Zellij session  ' --border=none --exit-0)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
# zellij_running=$(pgrep zellij)

# We're outside of zellij, so lets create a new session or attach to a new one.
if [[ -z $ZELLIJ ]]; then
	cd "$selected" || exit

	# -c will make zellij to either create a new session or to attach into an existing one
	zellij attach "$selected_name" -c
	exit 0
fi

# We're inside zellij so we'll open a new pane and move into the selected directory
zellij pipe --plugin file:~/.config/zellij/plugins/zellij-switch.wasm -- "$selected_name::$selected"

# Hopefully they'll someday support specifying a directory and this won't be as laggy
# thanks to @msirringhaus for getting this from the community some time ago!
# zellij action write-chars "cd $selected; clear" && zellij action write 10
