# theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = true
rulers = [80, 120, 160]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
