[ui]
default-command = "log"
editor = "nvim"
diff.format = "git"
pager = ["delta", "--diff-so-fancy"]

[merge-tools.diffconflicts]
program = "nvim"
merge-args = ["-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right"]
merge-tool-edits-conflict-markers = true

[merge-tools.delta]
program = "delta"
edit-args = ["$left", "$right"]

[aliases]
adv = ["bookmark", "move", "--to", "@-"]
auto = ["utils", ""]
roll = ["bookmark", "move", "--to", "@-"]
bm = ["bookmark"]
bmm = ["bookmark", "move", "master", "--to"]
fs = ["file"]
l = ["log", "-r", "@ | ancestors(remote_bookmarks().., 2) | trunk()"]
la = ["log", "-r", "all()"]
ld = ["log", "-r", "::@ & ~remote_bookmarks()"]
lp = [
    "log",
    "-r",
    "remote_bookmarks() & (mine() | committer(ben.mcdonald@2simple.com))",
]
lr = ["log", "-r", "remote_bookmarks()"]
lrm = ["log", "-r", "bookmarks() & ~(main | remote_bookmarks())"]
lrr = ["log", "-r", "mine() & bookmarks() & ~remote_bookmarks()"]
pu = ["git", "push"]
push = ["git", "push"]
pull = ["git", "pull"]
sq = ["squash"]
sw = ["edit"]
up = ["git", "fetch"]

[core]
fsmonitor = "watchman"
watchman.register_snapshot_trigger = true

[signing]
sign-all = true
backend = "ssh"
key = ""

[signing.backends.ssh]
program = "op-ssh-sign"
allowed-signers = "$HOME/.config/git/allowed_signers"

[git]
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"

[snapshot]
max-new-file-size = "64MiB"

[user]
name = ""
email = ""
