[General]
  snippetfile = "/home/bmc/.config/pet/snippet.toml"
  editor = "nvim"
  column = 40
  selectcmd = "fzf --ansi --layout=reverse --border --height=90% --pointer='*' --cycle --prompt='Snippets: '"
  backend = "gist"
  sortby = ""

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = false

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
  skip_ssl = false
