[env]
NODE_ENV = "production"

[tools]
ansible-base = "2.10.17"
bun          = "latest"
consul       = "1.14.3"
direnv       = "2.32.2"
erlang       = "25.3"
golang       = "1.20.3"
java         = "oracle-17"
lua          = "5.4.4"
nodejs       = "18"
opam         = "2.1.5"
opentofu     = "1.7.2"
pnpm         = "7.33.5"
python       = "system"
ruby         = "2.7.6"
rust         = "1.73.0"
terraform    = "1.9.1"
zig          = "0.10.1"
helm         = "3.15.2"
