[env]
NODE_ENV = "production"

[tools]
ansible-base = "2.10.17"
bun = "latest"
consul = "1.14.3"
direnv = "2.32.2"
erlang = "25.3"
go = "1.23.3"
helm = "3.15.2"
java = "oracle-17"
lua = "5.4.4"
nodejs = "18"
opam = "2.1.5"
opentofu = "1.7.2"
pnpm = "8"
python = "3.12"
ruby = "2.7.6"
rust = "1.80.1"
terraform = "1.9.1"
zig = "0.10.1"
